{
 "title": "Meilisearch",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Index", "label": "index", "query": { "query": "label_values(index)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Web application metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indexes Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meilisearch_index_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Documents",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meilisearch_index_docs_count{job=\"$job\", index=\"$Index\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Degraded Searches (1h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(meilisearch_degraded_search_requests{job=\"$job\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Searches (1h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(meilisearch_http_requests_total{method=\"POST\", path=\"/indexes/$Index/search\", job=\"$job\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Searches (24h)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(meilisearch_http_requests_total{method=\"POST\", path=\"/indexes/$Index/search\", job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "Total Searches (30d)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(meilisearch_http_requests_total{method=\"POST\", path=\"/indexes/$Index/search\", job=\"$job\"}[30d]))"
    }
   ]
  },
  {
   "title": "Database Size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "meilisearch_db_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Database size on disk"
    },
    {
     "expr": "meilisearch_used_db_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Used bytes"
    }
   ]
  },
  {
   "title": "Mean response time (All Indexes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(meilisearch_http_response_time_seconds_sum{instance=\"$instance\", job=\"$job\"}[5m]) / rate(meilisearch_http_response_time_seconds_count[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP status code",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(meilisearch_http_requests_total{instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (status)",
     "legendFormat": "HTTP Server - {{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "percentage of 4xx and 5xx HTTP responses over the total of the requests",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status) (rate(meilisearch_http_requests_total{status=~\"(4|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(status) group_left sum(rate(meilisearch_http_requests_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "HTTP Server - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP requests per second (All Indexes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(meilisearch_http_requests_total{instance=\"$instance\", job=\"$job\"}[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response time distribution over time (`POST /indexes/:index/search`)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(le) (increase(meilisearch_http_response_time_seconds_bucket{path=\"/indexes/$Index/search\", instance=\"$instance\", job=\"$job\"}[30s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of tasks by statuses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "meilisearch_nb_tasks{instance=\"$instance\", job=\"$job\", kind=\"statuses\"}",
     "legendFormat": "{{value}} "
    }
   ]
  },
  {
   "title": "Number of tasks by types",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "meilisearch_nb_tasks{instance=\"$instance\", job=\"$job\", kind=\"types\"}",
     "legendFormat": "{{value}} "
    }
   ]
  },
  {
   "title": "Number of tasks by indexes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "meilisearch_nb_tasks{instance=\"$instance\", job=\"$job\", kind=\"indexes\"}",
     "legendFormat": "{{value}} "
    }
   ]
  },
  {
   "title": "Task queue latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "meilisearch_task_queue_latency_seconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{value}} "
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[1m])",
       "legendFormat": "process"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name='mongodb-redis'}[1m])) by (name)",
       "legendFormat": "container"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"} / 1024 / 1024",
       "legendFormat": "process"
      },
      {
       "expr": "container_memory_usage_bytes{name=\"mongodb-redis\"} / 1024 / 1024",
       "legendFormat": "container"
      }
     ]
    }
   ]
  }
 ]
}